export const Categories = [
  { value: 'AI', label: 'AI' },
  { value: 'Blockchain', label: 'Blockchain' },
  { value: 'Cloud', label: 'Cloud' },
  { value: 'Crypto', label: 'Crypto' },
  { value: 'Data', label: 'Data' },
  { value: 'DevOps', label: 'DevOps' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Health', label: 'Health' },
  { value: 'IoT', label: 'IoT' },
  { value: 'Machine Learning', label: 'Machine Learning' },
  { value: 'Mobile', label: 'Mobile' },
  { value: 'Music', label: 'Music' },
  { value: 'Security', label: 'Security' },
  { value: 'Social', label: 'Social' },
  { value: 'Software', label: 'Software' },
  { value: 'Web', label: 'Web' },
  { value: 'Other', label: 'Other' },
];
